config/routes.rb
Rails.application.routes.draw do
	get 'questions/index'

	get 'questions/show'

	get 'questions/ajax_method'=>'questions#ajax_method',as:'ajax_method'

	get 'questions/button'=>'questions#button',as:'button'

	root 'logins#index'
	resource :login, only: %i{create destroy} 
  get 'login', to: 'logins#new'

	post 'register' => 'registers#create'
  get 'register', to: 'registers#new'

  resources :users

  #rake routes

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/archive.rb
class Archive < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
end

app/models/temporary.rb
class Temporary < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	SECURE = 'HOGEHOGEHOGEHOGEHOGEHOGEHOGEHOGEHOGEHOGEHOGEHOGEHOGE'
  CIPHER = 'aes-256-cbc'

	helper_method :current_user, :logged_in?

	before_action :current_user, only: [:index, :show, :button]

	def current_user
		if session[:user_id]
			@current_user||=User.find(session[:user_id])
		end
	end

	def logged_in?
		@current_user != nil
	end
end

app/controllers/concerns/ajax_helper.rb
module AjaxHelper
  def ajax_redirect_to(redirect_uri)
    { js: "window.location.replace('#{redirect_uri}');" }
  end
end

app/controllers/logins_controller.rb
class LoginsController < ApplicationController
	def index
		render "index"
	end

	def show
		render "new"
	end

	def new
  end

	def create
		user = User.find_by_name params[:name]
		if user && user.authenticate(params[:pass])
      session[:user_id] = user.id
      redirect_to root_path
    else
      flash.now.alert = "もう一度入力してください。"
      render "new"
    end
  end

  def destroy
  	session[:user_id] = nil
  	@current_user = nil
  	redirect_to root_path
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  include AjaxHelper

  @@answered=false
  @@reload_status='next'
  @@question_set=Question.new

  def index
  end

  def show
    @@answered=false
    @@questions=Question.all
    @num_of_questions=@@questions.length

    @@users=User.where(exist: true)

    #@question_set||=@@questions.sample
    if @@reload_status=='next'
      margin_max=Float::MAX
      @@questions.each do |q|
        if (current_user.theta-q.b).abs<margin_max
          margin_max=(current_user.theta-q.b).abs
          @@question_set=q
        end
      end
      @question=@@question_set
    else
      @question=@@questions.sample
    end

    collects=0
    @@questions.each do |q|
      collects+=eval("q.user#{current_user.number}")
    end
    @accuracy=collects/@@questions.length.to_f
  end

  def ajax_method
    if params[:reload].present?
      @@reload_status=params[:reload]
    end
    respond_to do |format|
      format.js{render ajax_redirect_to "http://localhost:3000/questions/show"}
    end
  end

  def button
    if params[:chosen].present?&&!@@answered
      if params[:chosen]==params[:answer]
        @result=1
      else
        @result=0
      end
      @@question_set.update("user#{current_user.number}": @result)
      @number_chosen=params[:btnid]
      @@answered=true
      current_user.exist=true
      current_user.save

      l_theta=Float::MIN
      -3.0.step(3.0,0.1) do |theta_arg|
        tmp_calc=1.0
        @@questions.each do |q|
          tmp_calc*=(1.0/(1.0+Math.exp(-1.7*(theta_arg-q.b))))**eval("q.user#{current_user.number}")*(1.0-1.0/(1.0+Math.exp(-1.7*(theta_arg-q.b))))**(1.0-eval("q.user#{current_user.number}"))
        end
        if l_theta<tmp_calc
          current_user.theta=theta_arg
          l_theta=tmp_calc
        end
      end
      current_user.save
      p "updated theta of user#{current_user.number}: "+current_user.theta.to_s
      l_b=Float::MIN
      -3.0.step(3.0,0.1) do |b_arg|
        tmp_calc=1.0
        @@users.each do |u|
          tmp_calc*=(1.0/(1.0+Math.exp(-1.7*(u.theta-b_arg))))**eval("@@question_set.user#{u.number}")*(1.0-1.0/(1.0+Math.exp(-1.7*(u.theta-b_arg))))**(1.0-eval("@@question_set.user#{u.number}"))
        end
        if l_b<tmp_calc
          @@question_set.b=b_arg
          l_b=tmp_calc
        end
      end
      @@question_set.save
      p "updated b of questions#{@@question_set.qid}: "+@@question_set.b.to_s

      f=File.open('./db/record.txt', 'w')
      record=""
      @@users.each do |u|
        @@questions.each do |q|
          record+="u_"+u.number.to_s+"_"+q.qid.to_s+"="+eval("q.user#{u.number}").to_s+";"
        end
      end
      f.print encrypt(record)
      f.close
    end
  end

  def encrypt(word)
    crypt = ActiveSupport::MessageEncryptor.new(SECURE, CIPHER)
    crypt.encrypt_and_sign(word)
  end

  def decrypt(word)
    crypt = ActiveSupport::MessageEncryptor.new(SECURE, CIPHER)
    crypt.decrypt_and_verify(word)
  end
end

app/controllers/registers_controller.rb
class RegistersController < ApplicationController
	def index
		render "index"
	end

	def show
		render "new"
	end

	def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if User.find_by(name: @user.name) == nil && @user.save
      @user.number = @user.id
      @user.save
      redirect_to root_path, notice: "ユーザ登録しました。"
    else
      render 'new'
    end
  end

  private

  def user_params
   params.require(:user).permit(:name, :password)
 end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/logins_helper.rb
module LoginsHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Quiz</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/logins/index.html.erb
<h1>学習システムver.1.2</h1>
<br><br>
<% if current_user==nil %>
<%= link_to "ログイン画面へ", login_path %>
<% else %>
<%= link_to '学習スタート！', 'http://localhost:3000/questions/show' %>
<br><br>
<%= link_to 'ログアウト', login_path, :confirm => 'ログアウトしますか？', :method => :delete %>
<% end %>

app/views/logins/new.html.erb
<h1>学習システムver.1.2</h1>

<br>

<h3>ログイン</h3>

<p><font color=red><%= flash[:alert] %></font></p>
<%= form_tag login_path do %>
<table id="login_form">
  <tr>
    <td><%= label_tag :name, 'UserID' %></td>
    <td><%= text_field_tag :name, params[:name] %></td>
  </tr>

  <tr>
    <td><%= label_tag :pass, 'Password' %></td>
    <td><%= password_field_tag :pass, params[:pass] %></td>
  </tr>

  <tr>
    <td><%= submit_tag "Login" %></td>
  </tr>
</table>
<% end %>

<br><br>
<%= link_to "ユーザ登録画面へ", register_path %>

app/views/questions/_partial1.html.erb
<% if @result==0 %>
<font size="6" color="blue">
<p>不正解</p>
</font>
<!--
<p>
<font size="4" color="white">
正解は
</font>
<font size="4" color="yellow">
<%= @collect_answer %>
</font>
</p>
-->
<% elsif @result==1 %>
<font size="6" color="red">
<p>正解！</p>
</font>
<% end %>

app/views/questions/button.js.erb
$("#result").html("<%= j render partial:'partial1' %>");
var button1 = document.getElementById(<%= @number_chosen %>);
<% if @result==1 %>
button1.style.backgroundColor = "red";
<% else %>
button1.style.backgroundColor = "blue";
<% end %>

app/views/questions/old/show1610.html.erb
<body style="margin-left:60px">
<h1>学習システムver.0.5</h1>
<br>

<p>(ノ-ロ-)ノ <%= @questions.length %> 問から</p><%=@result%>
<br><br>


<% @question=@questions.sample %>
<p><%= @question.question %></p>
<% @ch=Array[] %>
<% @ch[0]=@question.answer %>
<% @ch[1]=@question.dummy1 %>
<% @ch[2]=@question.dummy2 %>
<% @ch[3]=@question.dummy3 %>
<% @ch.shuffle! %>
<center>

<%= button_to "1. "+@ch[0], :remote=>true %>
<%= button_to "2. "+@ch[1], :remote=>true %>
<%= button_to "3. "+@ch[2], :remote=>true %>
<%= button_to "4. "+@ch[3], :remote=>true %>

<br><br><button id=0 onclick="judgment(id,'<%= @ch[0] %>');archive()" style="width:240px; height:30px">1. <%= @ch[0] %></button>
<br><br><button id=1 onclick="judgment(id,'<%= @ch[1] %>');archive()" style="width:240px; height:30px">2. <%= @ch[1] %></button>
<br><br><button id=2 onclick="judgment(id,'<%= @ch[2] %>');archive()" style="width:240px; height:30px">3. <%= @ch[2] %></button>
<br><br><button id=3 onclick="judgment(id,'<%= @ch[3] %>');archive()" style="width:240px; height:30px">4. <%= @ch[3] %></button>
<br><br><br>
<div id="result"></div>
<br><br>
<button onclick="next(id)" style="width:100px; height:30px">NEXT</button>
</center>
</body>


<script type="text/javascript">
answered=false

function judgment(id,choice){
if(answered==false){
$.ajax({url:'/questions/show/:result',type:'POST',dataType:'json',async:false,data:{result:1},});

if(choice=='<%= @question.answer %>'){
var button1 = document.getElementById(id);
button1.style.backgroundColor = "red";
document.getElementById("result").innerHTML='正解！';
$.ajax({url:'/questions/show/:result',type:'POST',dataType:'json',async:false,data:{result:1},});

}else{
var correct
<% 4.times do |i| %>
<% if(@ch[i]==@question.answer) then %>
correct = <%= i %>
<% end %>
<% end %>
var button1 = document.getElementById(id);
button1.style.backgroundColor = "blue";
var button2 = document.getElementById(correct);
button2.style.backgroundColor = "red";
document.getElementById("result").innerHTML='不正解';

}

answered=true
}
}

function next(){
window.location.reload();
}

function archive(){
<% @temp=Temporary.find(1) %>
<% Archive.create(qid:@question.qid,result:@result,one_before_qid:@temp.one_before_qid,one_before_result:@temp.one_before_result,two_before_qid:@temp.two_before_qid,two_before_result:@temp.two_before_result,three_before_qid:@temp.three_before_qid,three_before_result:@temp.three_before_result) %>
<% @temp.three_before_qid=@temp.two_before_qid %>
<% @temp.three_before_result=@temp.two_before_result %>
<% @temp.two_before_qid=@temp.one_before_qid %>
<% @temp.two_before_result=@temp.one_before_result %>
<% @temp.one_before_qid=@question.qid %>
<% @temp.one_before_result=@temp.result %>
<% @temp.save %>
}
</script>

app/views/questions/old/show1612.html.erb
<body style="margin-left:60px" onLoad="rect(<%= @accuracy %>)" bgcolor="#000000">
<font color="#ffffff">
<h1>学習システムver.0.4</h1>
<br>
<p><%= @questions.length %> 問から出題</p>
<br><br>
<% @question=@questions.sample %>
<p><%= @question.question %></p>
<% @qdata=Array[] %>
<% @qdata[0]=@question.answer %>
<% @qdata[1]=@question.dummy1 %>
<% @qdata[2]=@question.dummy2 %>
<% @qdata[3]=@question.dummy3 %>
<% @qdata.shuffle! %>
<% @qdata.push(@question.answer) %>
<center>
<br><br><%= button_to '1. '+@qdata[0],button_path(qid:@question.qid,chosen:@qdata[0],answer:@qdata[4]),method: :get,remote:true,id:1,style:"height:30px" %>
<br><br><%= button_to '2. '+@qdata[1],button_path(qid:@question.qid,chosen:@qdata[1],answer:@qdata[4]),method: :get,remote:true,id:2,style:"height:30px" %>
<br><br><%= button_to '3. '+@qdata[2],button_path(qid:@question.qid,chosen:@qdata[2],answer:@qdata[4]),method: :get,remote:true,id:3,style:"height:30px" %>
<br><br><%= button_to '4. '+@qdata[3],button_path(qid:@question.qid,chosen:@qdata[3],answer:@qdata[4]),method: :get,remote:true,id:4,style:"height:30px" %>
<br><br><br>
<div id="ajax1"></div>
<div id="result"></div>
<br><br>
<button onclick="next()" style="width:100px; height:30px">NEXT</button>
<br><br>
<canvas id="gauge"></canvas>
</center>
</font>
</body>
<script type="text/javascript">
function rect(accuracy){
if (HTMLCanvasElement) {
var canvas = document.getElementById('gauge');
var context = canvas.getContext('2d');
context.fillStyle = "rgb(0, 0, 255)";
context.fillRect(0,0,500,20);
context.fillStyle = "rgb(255, 0, 0)";
context.fillRect(0,0,500*accuracy,20);
}
}
function next(){
window.location.reload();
}
</script>

app/views/questions/show.html.erb
<body style="margin-left:60px" onLoad="rect(<%= @accuracy %>)" bgcolor="lemonchiffon">
	<font>
		<h1>学習システムver.1.2</h1>
		<div align="right" style="margin-right:150px"><%= link_to 'ログアウト', login_path, :confirm => 'ログアウトしますか？', :method => :delete %></div>
		<br>
		<p><%= @num_of_questions %> 問から出題</p>
		<br><br>
		<center>
			<p><%= image_tag @question.question %></p>
			<% @qdata=Array[] %>
			<% @qdata[0]=@question.answer %>
			<% @qdata[1]=@question.dummy1 %>
			<% @qdata[2]=@question.dummy2 %>
			<% @qdata[3]=@question.dummy3 %>
			<% @qdata.shuffle! %>
			<% @qdata.push(@question.answer) %>
			<br><br><%= button_to '1. '+@qdata[0],button_path(qid:@question.qid,chosen:@qdata[0],answer:@qdata[4],btnid:1),method: :get,remote:true,id:1,style:"height:30px" %>
			<br><br><%= button_to '2. '+@qdata[1],button_path(qid:@question.qid,chosen:@qdata[1],answer:@qdata[4],btnid:2),method: :get,remote:true,id:2,style:"height:30px" %>
			<br><br><%= button_to '3. '+@qdata[2],button_path(qid:@question.qid,chosen:@qdata[2],answer:@qdata[4],btnid:3),method: :get,remote:true,id:3,style:"height:30px" %>
			<br><br><%= button_to '4. '+@qdata[3],button_path(qid:@question.qid,chosen:@qdata[3],answer:@qdata[4],btnid:4),method: :get,remote:true,id:4,style:"height:30px" %>
			<br><br><br>
			<div id="result">
			</div>
			<br><br><%= button_to 'NEXT',ajax_method_path(reload:'next'),method: :get,remote:true,id:5,style:"height:30px" %>
			<br><br><%= button_to 'RANDOM',ajax_method_path(reload:'random'),method: :get,remote:true,id:6,style:"height:30px" %>
			<br><br>
			<canvas id="gauge"></canvas>
		</center>
	</font>
</body>
<script type="text/javascript">
	function rect(accuracy){
		if (HTMLCanvasElement) {
			var canvas = document.getElementById('gauge');
			var context = canvas.getContext('2d');
			context.fillStyle = "rgb(0, 0, 255)";
			context.fillRect(0,0,500,20);
			context.fillStyle = "rgb(255, 0, 0)";
			context.fillRect(0,0,500*accuracy,20);
		}
	}
</script>

app/views/registers/new.html.erb
<h1>学習システムver.1.2</h1>

<br>

<h3>ユーザ登録</h3>

<%= form_for(@user, url: { controller: :registers, action: :new }) do |f| %>

  <div class="field">
    <%= f.label :name, "UserID" %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :password_digest, "Password" %>
    <%= f.text_field :password %>
  </div>
  
  <div class="actions">
    <%= f.submit "Register" %>
  </div>
<% end %>

<br><br>
<%= link_to "ログイン画面へ", login_path %>